### ISSUE TITLE
No way to set the client IP address.

### ISSUE THREAD

**Issue by develroo** [nsg/tunnel#1]
So traditionally with tinc you set the client IP in the host file using something like

`Subnet = 10.4.0.30/32`

and in the tinc-up file like this

`ifconfig $INTERFACE 10.4.0.30 netmask 255.255.255.0
`

However I do not see any way to set this. Consequentially when I start tunnel it connects fine and brings up the interface fine but with no IP address and no routing `

There is no clear defined way to set the client IP using tunnel. Unless there is something I have missed ?

**Comment by nsg** [comment]
You are correct, I have not published the snap to the stable channel because I'm not sure what path to take to finish this project. Some feedback are welcome :)

Initially the idea was that tunnel would _only_ manage the tunnel, and leave IP assignment to some other tools. I focused on to package up Tinc and make it easy to get started. With the switch to Tinc 1.1 key management/exchange improved so I removed my own solutions and now it's closer to vanilla Tinc.

Now I'm split between the options of "just make this a tinc snap" or "make it even more user friendly". Currently I'm considering the later kind, but I'm not sure what type of users I like to target, servers? Desktops? The later kind would probably like a UI in GTK3, servers not so much. Possible a ncurses UI? Is it fine like it is, if I just add a few things like IP assignments?

What do you think? What do you think is the most common user for a snap like this? Initially I wrote this to easily mesh my servers and computers together.

**Comment by develroo** [comment]
Well in this instance I am using it to set up a Tinc VPN on a ubuntu snappy-core base with a nextcloud snap on top of it. The idea being I would connect over my Tinc network which I already have to other Nextcloud instances and federate them.

As for the typical case of installing tinc, I have to say the reason I prefer tinc over openvpn , which I have used for well over a decade now, was the simplicity of it's set up. You can in fact clone a nodes entire configuration, make a few minor edits to some files, generate a new key, copy the nodes host file with the new embedded public key in it and copy that to central server if you use one or to another node which you will be connecting to. 

Really it can be in 5 minutes tops. Which is whole lot simpler than openvpn. 

What I am trying to say is, other than when I have tinc on my phone/tablet or other touch device, setting up tinc doesn't really need a gui for anything. That being said I do like the simplicity of connecting to another host with tunnel and once following the guides it seemed pretty simple to to, the only caveat being of course in the end it is not functional. 

I think if you streamline the command line aspect then by it's very nature other gui tools can be laid upon them which is very much a unix thing to do. But if you want an example of a simple to use app like interface have a look at the [tinc app]( https://f-droid.org/en/packages/org.pacien.tincapp/) it is fairly intuitive though there are still some gotchas there if you are not paying attention. 

Aside from the fact I have no ip assigned it all works pretty well so far. Like I say I connected to my server fine, I just could not do anything after that because there was no network address to talk to.

**Comment by develroo** [comment]
For reference I think it is apposite to leave the example from the tinc-vpn website. for 1.1

https://tinc-vpn.org/documentation-1.1/Example-configuration.html#Example-configuration

**Comment by nsg** [comment]
Thank you for your feedback,

I will try to finish this project and make a proper release soon. I have released the current revision (73) to the beta channel if you like to use something a little more stable while I finalize this snap. The edge channel may contain a few experiments while I finish this.

**Comment by develroo** [comment]
Cheers. It is kinda cool that I can roll tinc into a embedded build like the one I am kinda doing. Kinda like the idea of Tinc being easy to IoT stuff for now.

**Comment by nsg** [comment]
Life got in the way, I have now released a release that I'm somewhat happy with. It's not that much more functionality but I have cleaned up the code a little.

* `tinc add` not asks for Address, Port and Subnet of the remote system. This information is optinal.
* You can also set the current IP, netmask and route with `snap set tunnel subnet=10.0.0.100/24`.

I hope I found all corner cases, time will tell I guess.

**Comment by develroo** [comment]
Heya, Cheers.. but do you know if the snap was pushed into arm as well? I don't see any updates. I am on this atm

`tunnel                 0.2             237    latest/edge    nsg`

`Linux nextcloud-home 4.4.0-1128-raspi2 #137-Ubuntu SMP Mon Jan 13 01:15:22 UTC 2020 armv7l armv7l armv7l GNU/Linux`

Thanks.

**Comment by nsg** [comment]
Indeed, both arm64 and armhf. Looks like you have the latest release already :)

![Screenshot_2020-08-07  Releases and revision history for tunnel ](https://user-images.githubusercontent.com/16388/89647393-cb553900-d8bd-11ea-9d81-a01b9329a081.png)

You can inspect the changes with `snap changes tunnel`, if you follow edge, I have done several updates over the last week.

**Comment by develroo** [comment]
Yeah.. I had to add both the address by hand and the route and then bring the interface down and up but it then started working. So not quite working on a reboot but getting there. 

Cheers.
